# Generated by Django 3.1.7 on 2021-03-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryarea',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('vfm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.countryarea')),
            ],
        ),
    ]
