# Generated by Django 3.1.7 on 2021-03-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_hotelreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='UUID',
            field=models.CharField(default=None, max_length=36),
        ),
    ]
