# Generated by Django 3.1.7 on 2021-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210316_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
    ]
