# Generated by Django 3.1.7 on 2021-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_hotel_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
