# Generated by Django 3.1.7 on 2021-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20210317_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryarea',
            name='bounding_box',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countryarea',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
