# Generated by Django 3.1.7 on 2021-03-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20210318_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'vfm', 'url', 'address')},
        ),
    ]
