# Generated by Django 3.1.7 on 2021-03-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20210319_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'vfm', 'url', 'country_area')},
        ),
    ]
